import { defineConfig } from "vitepress";
// Generated by `npm run docs:api` (see typedoc.json); the docs scripts always generate it first, so
// the API pages get their navigation without a hand-maintained copy of the class and interface list.
import typedocSidebar from "../api/typedoc-sidebar.json";

// The site source is tracked under `docs/`; `docs/api/`, `docs/.vitepress/cache/` and
// `docs/.vitepress/dist/` are build products (see .gitignore). Guides and contributor pages arrive
// with the content migration, which is also where the navigation gets its remaining entries.
export default defineConfig({
    title: "maxrects-packer",
    description: "MaxRects 2D bin packing for sprite sheets and texture atlases",
    base: "/maxrects-packer/",
    // Tracked designs and plans are repository records, not site pages.
    srcExclude: ["spec/**", "plans/**"],
    themeConfig: {
        search: { provider: "local" },
        nav: [
            { text: "API", link: "/api/" },
            { text: "GitHub", link: "https://github.com/soimy/maxrects-packer" }
        ],
        sidebar: { "/api/": typedocSidebar },
        socialLinks: [{ icon: "github", link: "https://github.com/soimy/maxrects-packer" }]
    }
});
